services:
  web:
    build:
      context: .
    image: status_page_django_app
    container_name: state_manager_server
    command: uvicorn project.asgi:application --host 0.0.0.0 --port 8000
    entrypoint: /app/entrypoint.sh
    volumes:
      - .:/app
    networks:
      - app-network

  celery:
    image: status_page_django_app
    restart: unless-stopped
    container_name: celery_worker
    command: celery -A project worker --loglevel=info
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge